#!/bin/bash
IFS=$'\n'
background_changer() {
    pics=`find #PICPATH# | grep -P ".*[.]png|.*[.]jpg|.*[.]jpeg|.*[.]PNG|.*[.]JPG|.*[.]JPEG"`
    for pic in $pics
    do
        gsettings set org.gnome.desktop.background picture-uri "file:///$pic"
        gsettings set org.gnome.desktop.screensaver picture-uri "file:///$pic"
        # echo $pic
        sleep #INTERVAL#
    done

}

while true
      do
          background_changer
done
